// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4peaU8dNcMgVxh6SLnOhWCS-Nf7vX6XU',
    appId: '1:867230118403:android:8d3f59ff827f2e1a0e5436',
    messagingSenderId: '867230118403',
    projectId: 'smartpowerswitch-e90d0',
    databaseURL: 'https://smartpowerswitch-e90d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpowerswitch-e90d0.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4km3NSCIFJbwKcY5dIBvkssC6IjRJAVM',
    appId: '1:867230118403:web:8f353f32e28392760e5436',
    messagingSenderId: '867230118403',
    projectId: 'smartpowerswitch-e90d0',
    authDomain: 'smartpowerswitch-e90d0.firebaseapp.com',
    databaseURL: 'https://smartpowerswitch-e90d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpowerswitch-e90d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQN2nxjv0-hrU_7kOpRvNe8EWySfmiUc',
    appId: '1:867230118403:ios:4ea9c7f9620aaf6d0e5436',
    messagingSenderId: '867230118403',
    projectId: 'smartpowerswitch-e90d0',
    databaseURL: 'https://smartpowerswitch-e90d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpowerswitch-e90d0.firebasestorage.app',
    iosBundleId: 'com.example.smartPowerSwitch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4km3NSCIFJbwKcY5dIBvkssC6IjRJAVM',
    appId: '1:867230118403:web:8df01c5c847fec0c0e5436',
    messagingSenderId: '867230118403',
    projectId: 'smartpowerswitch-e90d0',
    authDomain: 'smartpowerswitch-e90d0.firebaseapp.com',
    databaseURL: 'https://smartpowerswitch-e90d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartpowerswitch-e90d0.firebasestorage.app',
  );

}